FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# Copy both package and package-lock/... correct dest?
COPY package*.json ./

# Dependancies
RUN npm install

# Bundle app src
COPY . . 

# PORT to expose
EXPOSE 9001

COPY setup.sh .
# RUN /usr/src/app/dsSetup.sh

# Start app
CMD [ "npm", "start"]
