FROM node:carbon

# Create app directory
WORKDIR /usr/src/ctrl

RUN apt-get update
RUN apt-get -y install python-software-properties build-essential
RUN npm install wetty -g 
RUN [ "cp" "/usr/local/lib/node_modules/wetty/bin/wetty.conf" "/etc/init" ]
CMD [ "wetty" ]
