FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# Copy both package and package-lock/... correct dest?
COPY package*.json ./
RUN apt-get --assume-yes update
RUN apt-get --assume-yes install mysql-client

# Dependancies
RUN npm install
RUN npm install -g knex

# Bundle app src
COPY . . 
COPY dbsetup.sh .
RUN /usr/src/app/dbsetup.sh

RUN knex migrate:latest

# PORT to expose
EXPOSE 3010

# Start app
CMD [ "npm", "start"]
